### ISSUE TITLE
Permissions not open

### ISSUE THREAD

**Issue by tactmaster** [DDMoReThoughtflow/prov-infrastructure#1]
Hello,

I just wanted to test who got who got these messages :). Also this doesn't seem to be open to the public. I had to use a SSH key to clone it.

**Comment by stumoodie** [comment]
I got you email ;-).  The repo is definitely not private as you need to pay for a private repository.

I think the way it works is that if you are assigned a developer then you can clone it.  But if you are a member of the public then you need to fork the repository.



--------------------------------
Dr Stuart L Moodie
Director, Eight Pillars
Mob: +44 7951 015023

**Comment by kestrel99** [comment]
You are definitely assigned as a dev.

**Comment by tactmaster** [comment]
Yeap my mistake it.  The url it gave me was for a dev so you need a key even to read it.
